baseURL: "https://yanelpaulette.netlify.app/"
title: "Yanel Paulette"
theme: airspace-hugo
paginate: '4'
summaryLength: '30'
disableLanguages: []
disqusShortname: ''
googleAnalytics: ''
module:
  hugoVersion:
    extended: yes
    min: 0.83.1
outputs:
  home: HTML
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    endLevel: 6
    ordered: no
    startLevel: 2
params:
  author: Yanel Paulette
  contact:
    address_descriptors: no
    email: yanelpaulette@gmail.com
    form:
      action: '#'
      enable: yes
      success_image: images/work4.jpg
      use_netlify: yes
    location: "\r\n**Argentina**"
    phone: (011) 1549393976
  cookies:
    enable: yes
    expire_days: 2
  counter:
    enable: yes
    username: ''
  description: This is meta description
  #gmap:
    #enable: yes
    #gmap_api: AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU
    #map_latitude: '-35.151696044202914'
    #map_longitude: '-65.59897886628772'
    #map_marker: images/marker.png
  image: images/logo.png
  logo: images/logo.png
  logo_width: 100px
  plugins:
    css:
      - attributes: media='screen'
        link: plugins/bootstrap/css/bootstrap.min.css
      - attributes: ''
        link: plugins/ionicons/css/ionicons.min.css
      - attributes: ''
        link: plugins/magnific-popup/magnific-popup.min.css
      - attributes: ''
        link: plugins/slick/slick.css
    js:
      - attributes: ''
        link: plugins/jquery/jquery.min.js
      - attributes: ''
        link: plugins/bootstrap/js/bootstrap.min.js
      - attributes: ''
        link: plugins/slick/slick.min.js
      - attributes: ''
        link: plugins/magnific-popup/magnific-popup.min.js
      - attributes: ''
        link: plugins/shuffle/shuffle.min.js
      - attributes: defer
        link: plugins/google-map/gmap.js
  preloader:
    enable: yes
    preloader: ''
  social:
    #- icon: ion-social-googleplus-outline
    #  link: '#'
    - icon: ion-social-linkedin-outline
      link: 'https://www.linkedin.com/in/yanelpaulette/'
    #- icon: ion-social-pinterest-outline
    #  link: '#'
    #- icon: ion-social-dribbble-outline
    #  link: '#'
    - icon: ion-social-twitter-outline
      link: 'https://www.twitter.com/in/yanelpaulette/'
  widgets:
    sidebar:
      - recent_posts
      - taxonomy_category
      - taxonomy_tags
languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2021 [Themefisher](https://themefisher.com). All Rights
      Reserved.<br/> Created by Yanel Paulette.
    languageCode: en-US
    languageName: English
    menu:
      footer:
        - URL: about
          name: About
          weight: 1
        #- URL: project
          #name: Project
          #weight: 2
        #- URL: service
          #name: Service
          #weight: 3
        #- URL: pricing
          #name: Pricing
          #weight: 4
        #- URL: faq
          #name: FAQ
          #weight: 5
        - URL: contact
          name: Contact
          weight: 6
      #main:
        #- hasChildren: yes
          #name: More
          #weight: 5
    #weight: 1

